apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm516-20262-consulta-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consulta
  template:
    metadata:
      labels:
        app: consulta
    spec:
      containers:
        - name: ecm516-20262-consulta
          image: leoolivieri/ecm516-20262-consulta:2.0.0
          ports:
            - containerPort: 6000
          env:
            - name: URL_LEMBRETES
              value: "http://localhost:30000"
            - name: URL_OBSERVACOES
              value: "http://localhost:30001"
            - name: URL_CONSULTA
              value: "http://localhost:30002"
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: ecm516-20262-consulta-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: consulta
  ports:
    - name: consulta
      protocol: TCP
      port: 6000
      targetPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: ecm516-20262-consulta-nodeport-service
spec:
  type: NodePort
  selector:
    app: consulta
  ports:
    - name: consulta
      protocol: TCP
      port: 6000
      targetPort: 6000
      nodePort: 30002