apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm516-20262-classificacao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classificacao
  template:
    metadata:
      labels:
        app: classificacao
    spec:
      containers:
        - name: ecm516-20262-classificacao
          image: leoolivieri/ecm516-20262-classificacao:2.0.0
          ports:
            - containerPort: 7000
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: ecm516-20262-classificacao-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: classificacao
  ports:
    - name: classificacao
      protocol: TCP
      port: 7000
      targetPort: 7000