apiVersion: v1
kind: Pod
metadata:
  name: ecm-516-lembretes
spec:
  containers:
    - name: ecm-516-lembretes
      image: artruiz/lembretes:0.0.1
      resources:
        limits:
          memory: 256Mi
          cpu: 1